#import "cfg.typ": cfg
#show: cfg

= Groups
A group $:=$ a monoid where all elements are invertible.

A group is abelian $:=$ it's commutative.

A general linear group over a ring $R$ of an order $n :=
op("GL"_n) R :=
{A in op(L_n) R mid(|) det A != 0}$.

A special linear group over a ring $R$ of an order $n :=
op("SL"_n) R :=
{A in op(L_n) R mid(|) det A = 1}$.

A cyclic group generated by an element $a := angle.l a angle.r := {a^z mid(|) z}$.

An integer $z$ is a finite order of an element $a := a^z = 1$.

An element $a$ has an infinite order $:= exists.not$ a finite order of it.

*Cayley's theorem:* A finite group of an order $n$ is isomorphic to a subgroup of $S_n$.

$op("Aut") G :=$ a set of automorphisms of the group G.

A group of inner automorphisms of a group $G :=
op("Inn") G :=
{g |-> a g a^(-1) mid(|) a in G}$.

A kernel of a homomorphism $f in G'^G := {g mid(|) op(f) g = 1}$.

A monomorphism $:=$ an injective homomorphism.

An epimorphism $:=$ an surjective homomorphism.
