on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
      - run: find * -name "*.typ" -exec typst c --root=. {} \;
      - run: tree -H "." -I "index.html" -P "*.pdf" -o index.html
      - run: tar -cvf gh-pages.tar knowledge/*.pdf exers/*.pdf index.html
      - uses: actions/upload-artifact@v4
        with:
          name: "gh-pages"
          path: "gh-pages.tar"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps: 
      - uses: actions/deploy-pages@v4
        with:
          artifact_name: "gh-pages"
